apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: front-users
  namespace: openshift-gitops
  labels: 
    app: front-users
    type: frontend
spec:
  destination:
    namespace: demo
    server: "https://kubernetes.default.svc"
  source:
    path: apps/front-users/gitops
    repoURL: "https://github.com/dbgjerez/workshop-cdc"
    targetRevision: main
    helm:
      valueFiles:
      - 'dev.values.yaml'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
