apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: openshift-gitops
spec:
  destination:
    namespace: kafka
    server: "https://kubernetes.default.svc"
  source:
    path: gitops/tenants/kafka-cluster
    repoURL: {{ .Values.gitops.repo.url | quote }}
    targetRevision: {{ .Values.gitops.repo.revision | quote }}
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true