apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  annotations:
    strimzi.io/use-connector-resources: 'true'
  name: kafka
  namespace: kafka
spec:
  version: 3.5.0
  bootstrapServers: 'kafka-kafka-bootstrap:9092'
