apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  annotations:
    strimzi.io/use-connector-resources: 'true'
  name: kafka
  namespace: kafka
spec:
  config:
    group.id: kafka-connect
  image: quay.io/edeandrea/kafka-connect-debezium-mysql:amq-streams-1.4.0-dbz-1.1.0.Final
  bootstrapServers: 'kafka-kafka-bootstrap:9092'
