apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  labels:
    strimzi.io/cluster: kafka
  name: mariadb-debezium-users-fr
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  config:
    database.hostname: mariadb-s-users-fr.demo
    database.port: 3306
    database.user: root
    database.password: parking1234
    database.server.id: "223344"
    database.server.name: "mariadb-s-users-fr"
    database.whitelist: users
    topic.prefix: "demo.fr"
    schema.history.internal.kafka.topic: "history.demo"
    schema.history.internal.kafka.bootstrap.servers: 'kafka-kafka-bootstrap:9092'
    database.history.kafka.bootstrap.servers: 'kafka-kafka-bootstrap:9092'
    database.history.kafka.topic: "history.demo"
    include.schema.changes: "false" 
  tasksMax: 1