apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  labels:
    strimzi.io/cluster: kafka
  name: mariadb-debezium-users-spa
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  config:
    database.hostname: mariadb-users-spa.demo
    database.port: 3306
    database.user: root
    database.password: parking1234
    database.server.id: "184054"
    database.server.name: "mariadb-users-spa"
    database.whitelist: users
    topic.prefix: "demo"
    database.history.kafka.bootstrap.servers: 'kafka-kafka-bootstrap:9092'
    database.history.kafka.topic: "demo"
    include.schema.changes: "true" 
  tasksMax: 1