apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-connect
  namespace: openshift-gitops
spec:
  destination:
    namespace: kafka
    server: "https://kubernetes.default.svc"
  source:
    path: gitops/tenants/kafka-connect
    repoURL: "https://github.com/dbgjerez/workshop-cdc"
    targetRevision: main
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true