apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mariadb
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - app: users-fr
        namespace: demo
      - app: users-pt
        namespace: demo
  template:
    metadata: 
      name: 'mariadb-{{app}}'
      labels: 
        app: '{{app}}'
        type: database
    spec:
      destination:
        namespace: '{{namespace}}'
        server: "https://kubernetes.default.svc"
      source:
        path: gitops/tenants/mariadb/
        repoURL: "https://github.com/dbgjerez/workshop-cdc"
        targetRevision: main
        helm:
          valueFiles:
            - '{{app}}.values.yaml'
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - CreateNamespace=true    