apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operators
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-operators
    server: "https://kubernetes.default.svc"
  source:
    path: gitops/core/operators
    repoURL: "https://github.com/dbgjerez/workshop-cdc"
    targetRevision: 3-legacy-system-window
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
