apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ .Values.service.name | quote }}
    version: {{ .Values.service.version | quote }}
data:
  MONGODB_DATABASE: YWRtaW4=
  MONGODB_LOGIN_DATABASE: YWRtaW4xMjM0
  MONGODB_CONNECTION_STRING: bW9uZ29kYjovL2FkbWluOmFkbWluMTIzNEBtb25nb2RiOjI3MDE3