apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
spec:
  config:
    security:
      admin_user: "admin"
      admin_password: "admin1234"
    auth:
      disable_login_form: 'false'