apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ .Values.service.name | quote }}
    app: {{ .Values.service.name | quote }}
    version: {{ .Values.service.version | quote }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      name: {{ .Values.service.name | quote }}
  template:
    metadata:
      labels:
        name: {{ .Values.service.name | quote }}
        version: {{ .Values.service.version | quote }}
    spec:
      serviceAccountName: {{ .Values.service.name }}
      containers:
        - name: {{ .Values.service.name }}
          image: {{ .Values.service.image }}:{{ .Values.service.version }}
          envFrom:
            - secretRef:
                name: {{ .Values.service.name }}
          env:
          {{- range .Values.config.env }}
          {{- $envItem := . -}}
          {{- with $ }}
            - name: {{ $envItem.name | upper |  replace "-" "_" | quote}}
              value: {{ $envItem.value | quote }}
          {{- end }}
          {{- end }}
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: {{ .Values.kafka.bootstrap }}
          - name: KAFKA_DBZ_TOPIC_NAME
            value: {{ .Values.kafka.topic }}
          - name: APICURIO_REGISTRY_URL
            value: {{ .Values.kafka.api.avro }}
          - name: MONGODB_COLLECTION
            value: {{ .Values.mongodb.collection }}
          - name: ATLASMAP_MAPPER
            value: {{ .Values.atlas.mapper }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.deployment.health.liveness }}
              port: http
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: {{ .Values.deployment.health.readiness }}
              port: http
            failureThreshold: 10
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
---