apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ .Values.service.name | quote }}
    ns: {{ .Release.Namespace | quote }}
    version: {{ .Values.service.version | quote }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: {{ .Values.deployment.port }}
  selector:
    name: {{ .Values.service.name | quote }}
    ns: {{ .Release.Namespace | quote }}
status:
  loadBalancer: {}