apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-access-binding
  namespace: demo
subjects:
- kind: ServiceAccount
  name: default
  namespace: demo
roleRef:
  kind: Role
  name: configmap-access-role
  apiGroup: rbac.authorization.k8s.io
