apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    replicas: 3
    config:
      offsets.topic.replication.factor: 1
    listeners: 
      - name: plain
        port: 9092
        type: internal
        tls: false
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral