service:
  version: 0.2

deployment:
  port: 80
  health:
    liveness: /
    readiness: /

config:
  env:
    - name: SERVICE_NAME
      value: front-users-fr
    - name: SERVICE_VERSION
      value: 0.1