apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-{{ .Values.service.name }}
  labels:
    name: mariadb-{{ .Values.service.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300M