apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-{{ .Values.service.name }}
spec: # specification for deployment resource
  replicas: 1 
  selector:
    matchLabels:
      app: mariadb-{{ .Values.service.name }}
      name: mariadb-{{ .Values.service.name }}
  template: # blueprint for pods
    metadata:
      labels:
        app: mariadb-{{ .Values.service.name }} # service will look for this label
        name: mariadb-{{ .Values.service.name }}
    spec: # specification for pods
      containers: # we can have one or more containers
      - name: mariadb
        image: mariadb
        ports:
        - containerPort: 3306 
        env:
        - name: MARIADB_USER
          value: {{ .Values.mariadb.user }}
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-{{ .Values.service.name }}
              key: mariadb-password
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-{{ .Values.service.name }}
              key: mariadb-root-password
        - name: MARIADB_DATABASE
          value: {{ .Values.mariadb.database }}
        volumeMounts:
        - name: mariadb-pv
          mountPath: /var/lib/mysql
        - name: mariadb-{{ .Values.service.name }}
          mountPath: /etc/mysql/conf.d/
      volumes:
      - name: mariadb-{{ .Values.service.name }}
        configMap:
          name: mariadb-{{ .Values.service.name }}
      - name: mariadb-pv
        persistentVolumeClaim:
          claimName: mariadb-{{ .Values.service.name }}
