apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.service.name }}-pre-hook
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: pre-sync
        image: quay.io/openshift/origin-cli:latest
        command: ["sh", "-c"]
        args:
          - >
            URL=$(oc get route ms-users-camel -o jsonpath='{.spec.host}');
            oc create configmap {{ .Values.service.name }} --from-literal=config.js="var appConfig = {\"BACKEND_USERS_URL\": \"https://$URL\"};" --dry-run=client -o yaml | oc apply -f -
      restartPolicy: Never
