apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  to:
    kind: Service
    name: {{ .Values.service.name }}
  tls:
    termination: edge